### ISSUE TITLE
Research scroll driven animations

### ISSUE THREAD

**Issue by Daan645** [Daan645/lose-your-head-the-client-case#114]
I want to do research on scroll driven animations so I can use that on my about page.

**Comment by Daan645** [comment]
# Css scroll animations notes

## Scroll time line
U can define a scroll timeline. This wil check your scroll position in a div and triggers your animation.

example code:
```css
.scroll-container {
  height: 200vh; /* Simuleert een lange pagina */
  scroll-timeline-name: example-timeline;
  scroll-timeline-axis: block; /* Koppelt scrollen langs de verticale as */
}
```

## animation-timeline: scroll
This wil use your viewport and triggers the animation.

Example code: 
```css
animation-timeline: scroll(y or x); // define wich axis 
```

## animation timeline view
When u use animaiton timeline view, the animation will start when the assigned element enters the viewport, you can also define a delay in pixels.

Examplecode:
```css
animation-timeline: view(set delay in px: start value, end value); 
```

## animation range
animation range is a shorthandcode for animation start and end.

Example code:
```css
animation-range: 100px (start value) 200px (end value);
```

## Animation range contain and cover
```css
animation-start: cover 200px(add a offset);
```
This will start the animation when it enters the viewport.
```css
animation-start: contain 200px(add a offset);
```
This animation will start when the whole element is in the viewport.
You can also use it with the shorthand.
```css
animation-range: contain 100px (offset);
```

## animation range entry and exit
Entry will start the animation when the selected animation enters the viewport.

Example code:
```css
animation-range: entry;
```

Exit will start the animation when the selected animation is about to leave the viewport.

Example code:
```css
animation-range: exit;
```

## Animation forwards  (accesibillity) 
It is important to add a forwards to your animation. This will prevent the animation from stopping when its finished.

Example code:
```css
animation: 0.2s linear forwards;
```

## prefers reduced motion
Its important to make a media querie for people who have motion sickness. You dan do this by wrapping the animation in this code.

Example code:
```css
@media(prefers-reduced-motion: no-prefer) {
animation: fade-in linear forwards;
}
```
If the user has prefers reduced motion off on his system the animation will play, other whise it will not play.
