### ISSUE TITLE
Design about us page

### ISSUE THREAD

**Issue by Daan645** [Daan645/lose-your-head-the-client-case#115]
I want to make a design for the about page.

**Comment by Daan645** [comment]
## Scroll time line
U can define a scroll timeline. This wil check your scroll position in a div and triggers your animation.

example code:
```css
.scroll-container {
  height: 200vh; /* Simuleert een lange pagina */
  scroll-timeline-name: example-timeline;
  scroll-timeline-axis: block; /* Koppelt scrollen langs de verticale as */
}
```

## animation-timeline: scroll
This wil use your viewport and triggers the animation.

Example code: 
```css
animation-timeline: scroll(y or x); // define wich axis 
```
