### ISSUE TITLE
Week 1 | Coding Spike Jelte | Code

### ISSUE THREAD

**Issue by driezie** [Daan645/lose-your-head-the-client-case#123]

**Comment by driezie** [comment]
Voor dit project heeft Bramus een voorbeeld bij toegevoegd om te proberen. Hierbij wil ik dan ook verbinding maken van mijn api zodat je echte data kan zien in de lijst. Ik wil ook een kleine intro scherm maken die uiteindleijk weg gaat als je omlaag scrolt.

> Voorbeeld van Bramus
https://github.com/user-attachments/assets/ced998cd-ed6a-4dbf-9e50-c3ed3e446ce1

> Mijn voorbeeld
![Screenshot 2024-12-06 at 10 21 23](https://github.com/user-attachments/assets/01cddbe9-edf2-4606-a7bd-6e19b65be839)


## Hoe heb ik dit gemaakt
Ik vind het wel jammer dat de fotos zo'n slechte kwaliteit zijn maar dit komt omdat in de API de fotos al klein aangeleverd worden dus die kan ik niet vergroten.

Ik heb deze scroll functie gebruikt door een speciale class call toe te voegen aan de middelste colum. Dit heb ik niet gedaan via Sveltekit of Javascript maar ik heb met CSS de tweede tabel gepakt van de row door: `.schedule__radio-station-row:nth-of-type(2)`


hierop heb ik de class met `transform`, `flex-direction: column-reverse`, `animation` en `animation-timeline: scroll()`
```css
.schedule__radio-station-row:nth-of-type(2) {
    transform: translateY(calc(-100% + 100vh));
    flex-direction: column-reverse;
    animation: adjust-position linear forwards;
    animation-timeline: scroll(block);
    /* animation-range-end: 20vh; */
  }

De reden dat ik de `animation-range-end: 20vh` nog uit heb staan is omdat ik hiernog tests mee uitvoeren omdat je zo de scroll kan aanpassen waar dit begint en eindigt. Dit lijkt mij nog leuk om voor de volgende week hier meer mee te werken.

Ik heb ook een keyframe animatie gebruikt zodat ik de animatie kan doen
```css
/* Set up Animation */
@keyframes adjust-position {
	/* Start position: shift entire column up, but not so that it goes out of view */
	from {
		transform: translateY(calc(-100% + 100vh));
	}

	/* End position: shift entire column down, but not so that it goes out of view */
	to {
		transform: translateY(calc(100% - 100vh));
	}
}
```


## Testen

> Lighthouse test
Ik heb een lighthouse test gedaan op desktop. Hierop had ik geen javascript op de website dus  bij javascript had ik `100%`. Met accessibility had ik `94%` hiervoor kreeg ik een waarschuwing dat ik geen titel had op mijn head en ik zal hier ook een commit aan toevoegen. Bekijk commit [ca04add](https://github.com/Daan645/lose-your-head-the-client-case/pull/106/commits/ca04addea6bb88c491d3b143a35dbd73ed5fafd1).

Voor best practices had ik ook `100%`.

Bij SEO kreeg ik een niet goeie rating. Ik kreeg `82%`. Hierbij heb ik gekeken naar de tips en kreeg ik weer een title error en een meta beschrijving. Deze heb ik uiteindelijk aan dit project toegevoegd [ca04add](https://github.com/Daan645/lose-your-head-the-client-case/pull/106/commits/ca04addea6bb88c491d3b143a35dbd73ed5fafd1).
